version: '3.8'

services:
  identity-db:
    image: postgres:15-alpine
    container_name: identity_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: identity_db
    ports:
      - "5431:5432"
    networks:
      - supermart-network
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d identity_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  supermart-network:
    driver: bridge
    name: supermart-isolated-net

volumes:
  identity_db_data: